// client/app/dashboard/books/_components/book-card.tsx
'use client';

import Link from 'next/link';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardFooter, CardHeader, CardTitle } from '@/components/ui/card';
import { useAuthStore } from '@/store/auth';
import type { Book } from '@/types';

interface BookCardProps {
  book: Book;
}

export function BookCard({ book }: BookCardProps) {
  const isAdmin = useAuthStore((state) => state.isAdmin);

  const truncatedDescription =
    book.description && book.description.length > 100
      ? `${book.description.substring(0, 100)}...`
      : book.description || '';

  const publicationYear = book.publicationDate
    ? new Date(book.publicationDate).getFullYear()
    : 'N/A';

  return (
    <Card className="h-full flex flex-col">
      <CardHeader>
        <CardTitle className="text-lg font-semibold leading-none tracking-tight">
          {book.title}
        </CardTitle>
      </CardHeader>

      <CardContent className="flex-1 space-y-3">
        <p className="text-sm text-muted-foreground">by {book.authorName}</p>
        <p className="text-sm">{truncatedDescription}</p>
        <div className="flex items-center justify-between">
          <Badge variant="secondary">{book.genreName}</Badge>
          <span className="text-xs text-muted-foreground">{publicationYear}</span>
        </div>
      </CardContent>

      <CardFooter className="flex justify-between gap-2">
        <Button asChild variant="outline" size="sm" className="hover:cursor-pointer">
          <Link href={`/dashboard/books/${book.id}`}>View Details</Link>
        </Button>
        {isAdmin && (
          <Button variant="outline" size="sm" className="hover:cursor-pointer">
            <Link href={`/dashboard/books/${book.id}/edit`}>Edit</Link>
          </Button>
        )}
      </CardFooter>
    </Card>
  );
}

// frontend/src/components/shared/BookCard.vue
<script setup lang="ts">
import { computed } from 'vue'
import { useRouter } from 'vue-router'
import { useAuthStore } from '@/stores/auth'
import type { Book } from '@/types'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import Card from '@/components/ui/Card.vue'

interface Props {
  book: Book
}

const props = defineProps<Props>()
const router = useRouter()
const authStore = useAuthStore()

const isAdmin = computed(() => authStore.isAdmin)

const viewDetails = () => {
  router.push(`/dashboard/books/${props.book.id}`)
}

const editBook = () => {
  router.push(`/dashboard/books/${props.book.id}/edit`)
}
</script>

<template>
  <Card class="h-full">
    <template #header>
      <h3 class="font-semibold leading-none tracking-tight">{{ book.title }}</h3>
    </template>
    <div class="space-y-2">
      <p class="text-sm text-muted-foreground">by {{ book.authorName }}</p>
      <p class="text-sm">
        {{ book.description?.substring(0, 100) }}{{ book.description?.length > 100 ? '...' : '' }}
      </p>
      <div class="flex items-center justify-between">
        <Badge variant="secondary">{{ book.genreName }}</Badge>
        <span class="text-xs text-muted-foreground">
          {{ book.publicationDate ? new Date(book.publicationDate).getFullYear() : 'N/A' }}
        </span>
      </div>
    </div>
    <template #footer>
      <div class="flex items-center justify-between">
        <Button variant="outline" size="sm" @click="viewDetails">View Details</Button>/>
        <Button v-if="isAdmin" variant="outline" size="sm" @click="editBook">Edit</Button>
      </div>
    </template>
  </Card>
</template>
